color0   #141318
color1   #d65555
color2   #488d46
color3   #a57e5a
color4   #8363f9
color5   #a098bf
color6   #ccbeff
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #6bb16a
color11   #bc9a7a
color12   #c1b1ff
color13   #5551cc
color14   #6e52a6
color15   #ffffff

cursor #e6e1e9
cursor_text_color #cac4cf

foreground            #e6e1e9
background            #141318
selection_foreground  #322e41
selection_background  #cac3dc
url_color             #ccbeff