color0   #131313
color1   #d65555
color2   #478c46
color3   #bb8f67
color4   #995dea
color5   #a795bf
color6   #d8b9ff
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #7ac978
color11   #d6af8b
color12   #d0abff
color13   #6a4dc2
color14   #7c50a0
color15   #ffffff

cursor #e2e2e2
cursor_text_color #c6c6c6

foreground            #e2e2e2
background            #131313
selection_foreground  #352d40
selection_background  #cfc2da
url_color             #d8b9ff