set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",*tmux*:Tc"
set -ga terminal-overrides ',*:UTF-8'
set -g prefix C-a
unbind C-b
bind C-a send-prefix
unbind %
bind \\ split-window -h
unbind '"'
bind - split-window -v
unbind r
bind r source-file ~/.config/tmux/tmux.conf
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane
bg="#16181a"
bg_alt="#1e2124"
bg_highlight="#3c4048"
fg="#ffffff"
grey="#7b8496"
blue="#5ea1ff"
green="#5eff6c"
cyan="#5ef1ff"
red="#ff6e5e"
yellow="#f1ff5e"
magenta="#ff5ef1"
pink="#ff5ea0"
orange="#ffbd5e"
purple="#bd5eff"
set -g status-position top
set -g status-left-length 200
set -g status-right-length 200
set -g status-left "#[fg=${green},bold,bg=default] #S #[fg=${fg},nobold,bg=default] | "
set -g status-right " #{cpu}   #{mem} "
set -g status-justify left
set -g status-style "bg=default"
set -g window-status-format "#[fg=${fg},bg=default] #I:#W"
set -g window-status-current-format "#[fg=${cyan},bold,bg=default]  #[underscore]#I:#W"
set -g window-status-last-style "fg=${fg},bg=default"
set -g message-command-style "bg=default,fg=${fg}"
set -g message-style "bg=default,fg=${fg}"
set -g mode-style "bg=${blue},fg=${bg}"
set -g pane-active-border-style "fg=${blue},bg=default"
set -g pane-border-style "fg=${grey},bg=default"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
run '~/.config/tmux/plugins/tpm/tpm'
